[project]
name = "bank-client-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "mock-alchemy>=0.2.6",
    "pytest>=8.4.1",
    "ruff>=0.12.5",
    "sqlmodel>=0.0.24",
]
